### ISSUE TITLE
问个问题

### ISSUE THREAD

**Issue by solitudealma** [awarewen/my_dotfiles#3]
因为没您的联系方式，所以问一下配置文件中用到的icon那些文件是都上传了吗 还是说改了名字后没重新上传

**Comment by PILIHU2022** [comment]
请问你指的是哪个文件？我可能可以给予一些帮助

**Comment by solitudealma** [comment]
> 请问你指的是哪个文件？我可能可以给予一些帮助

我现在看到的是dunst,其他的暂时还不知道 因为也没截图或演示视频对比是哪个icon,也不想继续找其他人的配置

**Comment by PILIHU2022** [comment]
好的，我先看看

**Comment by PILIHU2022** [comment]
> > 请问你指的是哪个文件？我可能可以给予一些帮助
> 
> 我现在看到的是dunst,其他的暂时还不知道 因为也没截图或演示视频对比是哪个icon,也不想继续找其他人的配置

你指的是这个吗？
路径：Config/dunst/catppuccin_themes

**Comment by solitudealma** [comment]
> > > 请问你指的是哪个文件？我可能可以给予一些帮助
> 
> > 
> 
> > 我现在看到的是dunst,其他的暂时还不知道 因为也没截图或演示视频对比是哪个icon,也不想继续找其他人的配置
> 
> 
> 
> 你指的是这个吗？
> 
> 路径：Config/dunst/catppuccin_themes

dunstrc里也有

**Comment by PILIHU2022** [comment]
这是一个dunst的主题，可以直接使用，[这里](https://github.com/awarewen/my_dotfiles/tree/main/Config/dunst/catppuccin_themes)的README.md中有方法

**Comment by PILIHU2022** [comment]
我还在[此处](https://github.com/awarewen/my_dotfiles/tree/main/Home/.local/share/icons)找到了一些图标相关的，你可以看一下

**Comment by solitudealma** [comment]
> 这是一个dunst的主题，可以直接使用，[这里](https://github.com/awarewen/my_dotfiles/tree/main/Config/dunst/catppuccin_themes)的README.md中有方法

但是他的入口文件dunstc引用了自己的图

**Comment by solitudealma** [comment]
> 我还在[此处](https://github.com/awarewen/my_dotfiles/tree/main/Home/.local/share/icons)找到了一些图标相关的，你可以看一下

大概看了一下都是主题配置文件

**Comment by PILIHU2022** [comment]
> > 这是一个dunst的主题，可以直接使用，[这里](https://github.com/awarewen/my_dotfiles/tree/main/Config/dunst/catppuccin_themes)的README.md中有方法
> 
> 但是他的入口文件dunstc引用了自己的图

是指整个仓库的README.md还是指文件夹中的？如果是文件夹中的请给出路径或链接

**Comment by solitudealma** [comment]
> > > 这是一个dunst的主题，可以直接使用，[这里](https://github.com/awarewen/my_dotfiles/tree/main/Config/dunst/catppuccin_themes)的README.md中有方法
> > 
> > 
> > 但是他的入口文件dunstc引用了自己的图
> 
> 是指整个仓库的README.md还是指文件夹中的？如果是文件夹中的请给出路径或链接

不好意思，刚刚在吃饭，用手机回复的，犯了个错误，以为你能理解我的意思，我应该标出问题所在。
[这个文件](https://github.com/awarewen/my_dotfiles/blob/main/Config/dunst/dunstrc) 文件后面引用了作者自己的一些图，但是根据文件名没有在home找到对应的

**Comment by PILIHU2022** [comment]
> > > > 这是一个dunst的主题，可以直接使用，[这里](https://github.com/awarewen/my_dotfiles/tree/main/Config/dunst/catppuccin_themes)的README.md中有方法
> > > 
> > > 
> > > 但是他的入口文件dunstc引用了自己的图
> > 
> > 
> > 是指整个仓库的README.md还是指文件夹中的？如果是文件夹中的请给出路径或链接
> 
> 不好意思，刚刚在吃饭，用手机回复的，犯了个错误，以为你能理解我的意思，我应该标出问题所在。 [这个文件](https://github.com/awarewen/my_dotfiles/blob/main/Config/dunst/dunstrc) 文件后面引用了作者自己的一些图，但是根据文件名没有在home找到对应的

请稍等，我也要吃饭了😓

**Comment by solitudealma** [comment]
> > > > > 这是一个dunst的主题，可以直接使用，[这里](https://github.com/awarewen/my_dotfiles/tree/main/Config/dunst/catppuccin_themes)的README.md中有方法
> > > > 
> > > > 
> > > > 但是他的入口文件dunstc引用了自己的图
> > > 
> > > 
> > > 是指整个仓库的README.md还是指文件夹中的？如果是文件夹中的请给出路径或链接
> > 
> > 
> > 不好意思，刚刚在吃饭，用手机回复的，犯了个错误，以为你能理解我的意思，我应该标出问题所在。 [这个文件](https://github.com/awarewen/my_dotfiles/blob/main/Config/dunst/dunstrc) 文件后面引用了作者自己的一些图，但是根据文件名没有在home找到对应的
> 
> 请稍等，我也要吃饭了😓

不着急，你先去吃 我copy一下其他配置 估计只有这个dunst

**Comment by PILIHU2022** [comment]
作者没有上传，只能用自己的替代一下吧

**Comment by solitudealma** [comment]
> 作者没有上传，只能用自己的替代一下吧

ok

**Comment by solitudealma** [comment]
> 作者没有上传，只能用自己的替代一下吧

请问一下你知道ags的通知是怎么用的吗，哪个inotify-tools

**Comment by PILIHU2022** [comment]
> > 作者没有上传，只能用自己的替代一下吧
> 
> 请问一下你知道ags的通知是怎么用的吗，哪个inotify-tools

不好意思，那时候在睡觉。
README.md里的图片好像没有ags的通知吧？
图片上的都是ags的功能展示
我也用过ags，通知貌似是ags自带的（或者说是收录dunst的通知），你可以尝试一下

**Comment by PILIHU2022** [comment]
如果有需要我可以帮你联系作者

**Comment by awarewen** [comment]
> > 作者没有上传，只能用自己的替代一下吧
> 
> 请问一下你知道ags的通知是怎么用的吗，哪个inotify-tools

只需要安装 "inotify-tools" 即可，不过和其他的通知守护存在冲突，使用的时候需要关闭其他的通知服务，使用 "inotify-tools" 好处就是零成本的和 "ags 的通知中心" 一起使用。

**Comment by solitudealma** [comment]
> > > 作者没有上传，只能用自己的替代一下吧
> 
> > 
> 
> > 请问一下你知道ags的通知是怎么用的吗，哪个inotify-tools
> 
> 
> 
> 只需要安装 "inotify-tools" 即可，不过和其他的通知守护存在冲突，使用的时候需要关闭其他的通知服务，使用 "inotify-tools" 好处就是零成本的和 "ags 的通知中心" 一起使用。

嗯嗯 昨晚解决了 少装了个gnome-blutooth3.0 可惜ags的通知不好独立出来 再找找其他人的dunst 而且感觉ags反应有点慢

**Comment by solitudealma** [comment]
> > > 作者没有上传，只能用自己的替代一下吧
> 
> > 
> 
> > 请问一下你知道ags的通知是怎么用的吗，哪个inotify-tools
> 
> 
> 
> 不好意思，那时候在睡觉。
> 
> README.md里的图片好像没有ags的通知吧？
> 
> 图片上的都是ags的功能展示
> 
> 我也用过ags，通知貌似是ags自带的（或者说是收录dunst的通知），你可以尝试一下

没事啦 解决了 我本来以为通知可以独立的 结果是和bar绑定的 暂时还不想换bar

**Comment by awarewen** [comment]
> > 这是一个dunst的主题，可以直接使用，[这里](https://github.com/awarewen/my_dotfiles/tree/main/Config/dunst/catppuccin_themes)的README.md中有方法
> 
> 但是他的入口文件dunstc引用了自己的图

我这里 "dunst" 是作为 "inotify-tools" 的备选，默认使用 "notify-send -i /path/to/icon"

**Comment by awarewen** [comment]
> > > > 作者没有上传，只能用自己的替代一下吧
> > 
> > 
> > > 
> > 
> > 
> > > 请问一下你知道ags的通知是怎么用的吗，哪个inotify-tools
> > 
> > 
> > 不好意思，那时候在睡觉。
> > README.md里的图片好像没有ags的通知吧？
> > 图片上的都是ags的功能展示
> > 我也用过ags，通知貌似是ags自带的（或者说是收录dunst的通知），你可以尝试一下
> 
> 没事啦 解决了 我本来以为通知可以独立的 结果是和bar绑定的 暂时还不想换bar

好哒～

**Comment by solitudealma** [comment]
> > > > > 作者没有上传，只能用自己的替代一下吧
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > 请问一下你知道ags的通知是怎么用的吗，哪个inotify-tools
> > > 
> > > 
> > > 不好意思，那时候在睡觉。
> > > README.md里的图片好像没有ags的通知吧？
> > > 图片上的都是ags的功能展示
> > > 我也用过ags，通知貌似是ags自带的（或者说是收录dunst的通知），你可以尝试一下
> > 
> > 
> > 没事啦 解决了 我本来以为通知可以独立的 结果是和bar绑定的 暂时还不想换bar
> 
> 好哒～

能不能上传一下record-script.sh这个录制脚本
